#include "../include/mt_lpx_saccade.h"
#include <cmath>
#include <cstdio>

// Global variables - exactly matching JavaScript
double FOVEA_LEN = 0.0;                         // Value determined at startup
LR_t LR;                                        // Global LR object

/**
 * Returns an unsigned pseudo-random 32-bit integer in range 
 * [0, 2^32-1]. This is the basic method for generating
 * random values. It requires only a single multiply and 
 * a single add to produce a statistically uniform (but not 
 * cryptographically secure) pseudo-random value (source Knuth). 
 * 
 * @param rv The last pseudo-random number generated 
 * by this function (or a seed) which is used to generate the 
 * current one.
 * 
 * @returns The pseudo-random integer which must be 
 * passed back into this function to get the next one.
 */
uint32_t randInt32(uint32_t rv) {
    return (1664525 * rv + 1013904223) & 0xFFFFFFFF;
}

/**
 * Returns a random integer uniformly distributed in 
 * [0, n-1] for argument n and a pseudo-random value rv
 * generated by randInt32().
 * 
 * @param n The range.
 * @param rv The pseudo-random number from randInt32().
 * 
 * @returns A pseudo-random integer in the 
 * requested range.
 */
int getIntInRange(int n, uint32_t rv) {
    return (int)floor(n * 2.3283064365387e-10 * rv);
}

/**
 * Returns a random float uniformly distributed in 
 * [low, high) for arguments low, high and a 
 * pseudo-random value rv generated by randInt32().
 * 
 * @param low The lowest range value.
 * @param high The highest range value.
 * @param rv The pseudo-random number from randInt32().
 * @returns A pseudo-random float in the 
 * requested range.
 */
double getFloatInRange(double low, double high, uint32_t rv) {
    return (high - low) * 2.3283064365387e-10 * rv + low;
}

/**
 * Generates a random value from a geometric distribution 
 * of interval values. Returns the number of trials to the 
 * next successful trial given the probability p of success
 * on a trial.
 * 
 * @param p The probability of success on a trial.
 * @param rv A pseudo-random value from randInt32().
 * @returns The number of trials to the next success.
 */
int geometric(double p, uint32_t rv) {
    double u = getFloatInRange(0.0, 1.0, rv);
    return (int)ceil(log(1.0 - u) / log(1.0 - p));
}

/**
 * Selects an array element from pDensity[] probabilistically by its
 * relative weight in the array and returns the index of that element.
 * 
 * @param pDensity The probability density function array, the 
 * sum of the elements of which must equal 1.0. Element order has 
 * no effect.
 * 
 * @param len The length of the array.
 * 
 * @param rv A pseudo-random int32 from randInt32().
 */
int getDiscreteRV(const std::vector<double>& pDensity, int len, uint32_t rv) {
    double rv2 = 2.3283064365387e-10 * rv;
    double intvl = 0.0;
    
    int n = len - 1;
    for (int i = 0; i < n; i++) {
        intvl += pDensity[i];
        if (intvl >= rv2) {
            return i;
        }
    }
    return len - 1;
}

/**
 * Verifies that x + mov_x and y + mov_y are within 
 * the bounds of the video frame.
 * 
 * @param mov_x The amount by which the x location 
 * will be displaced
 * 
 * @param mov_y The amount by which the y location
 * will be displaced
 * 
 * @param x The current x scan location coordinate
 * @param y The current y scan location coordinate
 * 
 * @returns True if verified else false.
 */
bool posIsInRange(double mov_x, double mov_y, double x, double y) {
    double nxt_x = x + mov_x;
    double nxt_y = y + mov_y;
    if (nxt_x > X_LOW && nxt_x < X_HIGH &&
        nxt_y > Y_LOW && nxt_y < Y_HIGH) {
        return true;
    }
    return false;
}

/**
 * Gets the location displacement that occurred between 
 * the current and previous frames.
 * 
 * @param lr The identifier for the left, L, or 
 * right, R, camera data object.
 *
 * @returns The location displacement.
 */
double displacement(void* lr) {
    CameraData* camera = (CameraData*)lr;
    double dx = camera->x - camera->x_last;
    double dy = camera->y - camera->y_last;
    return sqrt(dx * dx + dy * dy);
}

/**
 * Forces a random saccade even while detecting motion 
 * when the motion location displacement is less than 
 * BREAKAWAY_LIMIT. As long as the displacement continues 
 * to be less than BREAKAWAY_LIMIT, the saccade will 
 * occur after a delay of 2 * MAX_SACCADE_COUNT frames.
 * 
 * @param lpG The LPGazeControl object that 
 * calls this function.
 * 
 * @param lr The identifier for the left, L, or 
 * right, R, camera data object.
 *
 * @returns Returns true while lr.breakaway_count 
 * is greater than MAX_SACCADE_COUNT else false.
 */
bool breakGaze(LPGazeControl* lpG, void* lr) {
    CameraData* camera = (CameraData*)lr;
    
    if (displacement(lr) >= BREAKAWAY_LIMIT) {
        camera->breakaway_count = 0;
    }
    else {
        camera->breakaway_count += 1;
        if (camera->breakaway_count > MAX_SACCADE_COUNT) {
            camera->x_last = camera->x;
            camera->y_last = camera->y;
            return true;
        }
    }
    
    camera->x_last = camera->x;
    camera->y_last = camera->y;
    
    return false;
}

/**
 * Does a saccade to a new movement location if 
 * a saccade did not occur on the previous frame 
 * and lr.disableSaccadeCount has counted down 
 * to zero. Movement detection continually sets 
 * lr.disableSaccadeCount to MAX_SACCADE_COUNT 
 * thus preventing the countdown to zero unless 
 * the set operation is blocked by breakGaze(), 
 * in which case the countdown to zero proceeds 
 * after an additional delay of MAX_SACCADE_COUNT
 * frames.
 * 
 * @param lpG The LPGazeControl object that 
 * calls this function.
 * 
 * @param lr The identifier for the left, L, or 
 * right, R, camera data object.
 */
void doMovementSaccade(LPGazeControl* lpG, void* lr) {
    CameraData* camera = (CameraData*)lr;
    
    camera->x += lpG->saccade.mov_x;        // Assign the mover location
    camera->y += lpG->saccade.mov_y;
    
    camera->noSaccade = false;
    
    if (distanceLR(lpG) > LR.maxDist) {
        assignLocationFromMover(lpG);
    }
    else if (LR.areTracking) {
        setTrackingDifference(lpG, lr);     // Assign the non-mover location
    }
    
    if (camera->breakaway_count <= MAX_SACCADE_COUNT) {
        camera->disableSaccadeCount = MAX_SACCADE_COUNT;
    }
}

/**
 * Assigns the location data from a random saccade.
 * 
 * @param lpG The LPGazeControl object that calls this 
 * function.
 * 
 * @param lr The identifier for the left, L, or right, 
 * R, camera data object.
 */
void doRandomSaccade(LPGazeControl* lpG, void* lr) {
    CameraData* camera = (CameraData*)lr;
    
    if (lpG->saccade.reZero == true) {
        camera->x = 0.0;
        camera->y = 0.0;
    }
    else {
        if (camera->isSaccadeMaster) {
            camera->x += lpG->saccade.rnd_x;
            camera->y += lpG->saccade.rnd_y;
        }
        else {
            assignMasterLocationToSlave(lpG);
        }
    }
    camera->noSaccade = false;
    LR.areTracking = false;
    LR.minTrackDiff = 1.0;
}

/**
 * Assigns the location data from an externally commanded
 * saccade.
 * 
 * @param lr The identifier for the left, L, or right, 
 * R, camera data object.
 */
void doCommandedSaccade(void* lr) {
    CameraData* camera = (CameraData*)lr;
    
    if (posIsInRange(camera->mov_x, camera->mov_y, 0.0, 0.0)) {
        camera->x = camera->mov_x;
        camera->y = camera->mov_y;
        camera->noSaccade = false;
    }
    camera->isCommand = false;
}

/**
 * Gets distance between current scan locations 
 * at left and right cameras.
 * 
 * @param lpG The LPGazeControl object that 
 * calls this function.
 * 
 * @returns Distance
 */
double distanceLR(LPGazeControl* lpG) {
    double dx = lpG->R.x - lpG->L.x;
    double dy = lpG->R.y - lpG->L.y;
    return sqrt(dx * dx + dy * dy);
}

/**
 * Assigns the scan location of the camera that 
 * detects movement to the other camera if the 
 * distance between the scan locations exceeds 
 * LR.maxDist.
 * 
 * @param lpG The LPGazeControl object that 
 * calls this function.
 */
void assignLocationFromMover(LPGazeControl* lpG) {
    if (lpG->R.isMoving) {
        lpG->L.x = lpG->R.x;
        lpG->L.y = lpG->R.y;
    }
    else {
        lpG->R.x = lpG->L.x;
        lpG->R.y = lpG->L.y;
    }
}

/**
 * Assigns the current scan location of 
 * master camera to the slave camera.
 * 
 * @param lpG The LPGazeControl object 
 * that calls this function.
 */
void assignMasterLocationToSlave(LPGazeControl* lpG) {
    if (lpG->R.isSaccadeMaster) {
        lpG->L.x = lpG->R.x;
        lpG->L.y = lpG->R.y;
    }
    else {
        lpG->R.x = lpG->L.x;
        lpG->R.y = lpG->L.y;
    }
}

/**
 * Assigns a fixed offset between left and right
 * camera scan locations when LR.areTracking is 
 * true.
 * 
 * @param lpG The LPGazeControl object that 
 * calls this function.
 * 
 * @param lr The identifier for the left, 
 * L, or right, R, camera data object.
 */
void setTrackingDifference(LPGazeControl* lpG, void* lr) {
    CameraData* camera = (CameraData*)lr;
    double x = camera->x + LR.xDiff;
    double y = camera->y + LR.yDiff;
    
    if (posIsInRange(0.0, 0.0, x, y)) {
        if (camera == &(lpG->R)) {
            lpG->L.x_track = x;
            lpG->L.y_track = y;
            lpG->L.use_tracking = true;
        }
        else {
            lpG->R.x_track = x;
            lpG->R.y_track = y;
            lpG->R.use_tracking = true;
        }
    }
}

/**
 * Assigns the right to left tracking difference 
 * to lr.x and lr.y when lr.use_tracking is true.
 * 
 * @param lr The identifier for the left, L, 
 * or right, R, camera data object.
 */
void useTrackingDifference(void* lr) {
    CameraData* camera = (CameraData*)lr;
    camera->x = camera->x_track;
    camera->y = camera->y_track;
    camera->noSaccade = false;
    camera->use_tracking = false;
}

/**
 * Selects the x, y location of a moving LPRetinaImage cell 
 * probablistically from a region of moving cells in the
 * most recent LPRetinaImage.
 * 
 * @param lpG The LPGazeControl object that calls
 * this function.
 * 
 * @param lr The identifier for the left, L, or 
 * right, R, camera data object.
 */
void locateMovement(LPGazeControl* lpG, void* lr) {
    CameraData* camera = (CameraData*)lr;
    
    camera->isMoving = false;
    
    // Early exit if we don't have both current and previous retina images
    if (camera->lpRetina == nullptr || camera->lpRetina0 == nullptr) {
        lpG->saccade.mov_x = 0.0;
        lpG->saccade.mov_y = 0.0;
        return;
    }
    
    // Cast to LPXVision pointers
    lpx_vision::LPXVision* lpV = static_cast<lpx_vision::LPXVision*>(camera->lpRetina);
    lpx_vision::LPXVision* lpV0 = static_cast<lpx_vision::LPXVision*>(camera->lpRetina0);
    
    // Use the real LPXVision Hamming distance method
    int retinaLength = static_cast<int>(lpV0->retinaCells.size());
    if (retinaLength == 0) {
        lpG->saccade.mov_x = 0.0;
        lpG->saccade.mov_y = 0.0;
        return;
    }
    
    std::vector<double> hDiffArray = lpV->getHammingDistanceArray(lpV0, 0, retinaLength);
    
    std::vector<double> pDensity;
    std::vector<int> hdIdx;
    
    double accum = 0.0;
    int countM = 0;
    
    for (int i = (int)FOVEA_LEN; i < (int)hDiffArray.size(); i++) {
        double hDiff = hDiffArray[i];
        
        if (hDiff >= MIN_MOVING_DIFF) {
            double p = (hDiff - MIN_MOVING_DIFF);
            pDensity.push_back(p);
            hdIdx.push_back(i);
            accum += p;
            countM++;
        }
    }
    
    if (countM > MIN_MOVING_COUNT) {
        double norm = 1.0 / accum;
        
        for (int i = 0; i < countM; i++) {
            pDensity[i] *= norm;
        }
        
        lpG->rv = randInt32(lpG->rv);
        int k = getDiscreteRV(pDensity, countM, lpG->rv);
        
        int hDiffIdx = hdIdx[k];
        
        // Use the real LPXVision geometry method
        lpx_vision::LPXVision::CellPosition location = lpV->getLPXCellPosition(hDiffIdx, lpV->spiralPer);
        
        if (posIsInRange(location.x, location.y, camera->x, camera->y)) {
            lpG->saccade.mov_x = location.x;
            lpG->saccade.mov_y = location.y;
            camera->isMoving = true;
            lpG->saccade.isRandom = false;
            return;
        }
    }
    
    // Fallback when no movement detected
    lpG->saccade.mov_x = 0.0;
    lpG->saccade.mov_y = 0.0;
}

/**
 * Selects a random location in an image that is 
 * visually distinct from surrounding points.
 * 
 * @param lpG The LPGazeControl object that 
 * calls this function.
 * 
 * @param lr The identifier for the left, L, 
 * or right, R, camera data object.
 */
void selectRandomLocation(LPGazeControl* lpG, void* lr) {
    CameraData* camera = (CameraData*)lr;
    
    // NOTE: This function also requires LPRetinaImage implementation
    // For now, providing skeleton that matches JavaScript logic
    
    /*
    LPRetinaImage* lpV = (LPRetinaImage*)camera->lpRetina;
    
    lpG->saccade.count += 1;
    lpG->saccade.isRandom = false;
    
    if (lpG->saccade.count < lpG->saccade.maxCount) {  // Count down the no-saccade wait time.
        lpG->saccade.mov_x = 0.0;
        lpG->saccade.mov_y = 0.0;
        lpG->saccade.reZero = false;
        return;
    }
    
    // Otherwise, generate a new random wait-length saccade
    lpG->rv = randInt32(lpG->rv);
    
    const int start = 3500;  // Search only the top half of lpV cell arrays (foveaLen63 is 2730)
                            // because cells with large hDiffs are rare in lower half.
    
    std::vector<double> hDiffs = lpV->getLocalHammingDistances(start);
    
    double maxDiff = 0.75;
    std::vector<int> idx;
    
    for (int i = start; i < lpV->length; i++) {  // Fill idx[] array with locations having large
        if (hDiffs[i] > maxDiff) {               // local hDiffs over the scan range.
            Position pos = lpV->geometry->getLPXCellPosition(i, lpV->spiralPer);
            if (posIsInRange(pos.x, pos.y, camera->x, camera->y)) {
                idx.push_back(i);
            }
        }
    }
    
    lpG->saccade.rnd_x = 0.0;
    lpG->saccade.rnd_y = 0.0;
    lpG->saccade.count = 0;
    lpG->saccade.isRandom = true;
    
    if (idx.size() > 0) {  // If an in-range saccade was obtained
        lpG->rv = randInt32(lpG->rv);
        int n = getIntInRange(idx.size(), lpG->rv);
        Position pos = lpV->geometry->getLPXCellPosition(idx[n], lpV->spiralPer);
        
        lpG->saccade.rnd_x = pos.x;  // save the location.
        lpG->saccade.rnd_y = pos.y;
        lpG->saccade.reZero = false;
        return;
    }
    */
    
    // If no in-range saccade was obtained or LPRetinaImage not available
    lpG->saccade.reZero = true;  // set the reZero flag.
}

// Position struct for coordinates
struct Position {
    double x;
    double y;
    Position(double x = 0.0, double y = 0.0) : x(x), y(y) {}
};

/**
 * HammingDistance utility class for efficient bit counting using lookup table
 * Exactly matching the JavaScript onesCount approach from the test files
 */
class HammingDistance {
private:
    static std::array<uint8_t, 65536> onesCount;  // 2^16 lookup table (64KB)
    static bool initialized;
    
public:
    /**
     * Initialize the ones count lookup table
     * Based on makeOnesCountTable() from JavaScript test files
     */
    static void initialize() {
        if (initialized) return;
        
        for (int i = 0; i < 65536; i++) {
            int count = 0;
            int val = i;
            for (int j = 0; j < 16; j++) {  // Count bits in 16-bit value
                if ((val & 1) == 1) {
                    count += 1;
                }
                val >>= 1;
            }
            onesCount[i] = count;
        }
        initialized = true;
    }
    
    /**
     * Count ones in 32-bit value using lookup table
     * Matches JavaScript approach: lower 16 bits + upper 16 bits
     */
    static int popcount32(uint32_t value) {
        return onesCount[value & 0xFFFF] +           // Lower 16 bits
               onesCount[(value >> 16) & 0xFFFF];    // Upper 16 bits
    }
};

// Static member definitions
std::array<uint8_t, 65536> HammingDistance::onesCount;
bool HammingDistance::initialized = false;

/**
 * Missing LPXVision Hamming distance method implementations
 * These were called in the JavaScript but never implemented
 */

/**
 * Gets Hamming distance array between two LPXVision objects
 * Reconstructed from JavaScript usage in locateMovement function
 * 
 * @param lpVision1 First LPXVision object
 * @param lpVision2 Second LPXVision object  
 * @param start Starting index in retina cells
 * @param length Number of cells to compare
 * @returns Array of normalized Hamming distances (0.0 to 1.0)
 */
std::vector<double> getHammingDistanceArray(void* lpVision1, void* lpVision2, int start, int length) {
    // NOTE: This is a placeholder implementation since we don't have access to LPXVision internals
    // In real implementation, would cast to LPXVision* and access retinaCells vector
    
    /*
    LPXVision* lpV1 = (LPXVision*)lpVision1;
    LPXVision* lpV2 = (LPXVision*)lpVision2;
    
    std::vector<double> result(length);
    
    HammingDistance::initialize();  // Ensure lookup table is ready
    
    for (int i = 0; i < length; i++) {
        uint32_t cell1 = lpV1->retinaCells[start + i];  // Assuming 32-bit cells
        uint32_t cell2 = lpV2->retinaCells[start + i];
        uint32_t xor_val = cell1 ^ cell2;
        
        // Normalize by maximum possible bit differences (32 bits)
        result[i] = static_cast<double>(HammingDistance::popcount32(xor_val)) / 32.0;
    }
    
    return result;
    */
    
    // Placeholder return for compilation
    std::vector<double> result(length, 0.0);
    return result;
}

/**
 * Gets local Hamming distances within a single LPXVision object
 * Reconstructed from JavaScript usage in selectRandomLocation function
 * 
 * @param lpVision LPXVision object
 * @param start Starting index (default 0)
 * @returns Array of local Hamming distances between adjacent cells
 */
std::vector<double> getLocalHammingDistances(void* lpVision, int start = 0) {
    // NOTE: This is a placeholder implementation since we don't have access to LPXVision internals
    // In real implementation, would cast to LPXVision* and access retinaCells vector
    
    /*
    LPXVision* lpV = (LPXVision*)lpVision;
    
    int arrayLength = lpV->retinaCells.size() - start;
    std::vector<double> result(arrayLength);
    
    HammingDistance::initialize();  // Ensure lookup table is ready
    
    for (int i = start; i < static_cast<int>(lpV->retinaCells.size()) - 1; i++) {
        uint32_t cell1 = lpV->retinaCells[i];      // Current cell
        uint32_t cell2 = lpV->retinaCells[i + 1];  // Next cell
        uint32_t xor_val = cell1 ^ cell2;
        
        // Normalize by maximum possible bit differences (32 bits)
        result[i - start] = static_cast<double>(HammingDistance::popcount32(xor_val)) / 32.0;
    }
    
    return result;
    */
    
    // Placeholder return for compilation
    std::vector<double> result(100, 0.5);  // Dummy data
    return result;
}
